ALTER TABLE users ADD COLUMN IF NOT EXISTS notify_installment BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notify_debt BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notify_days_before INTEGER DEFAULT 3;
