// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID             string      `json:"id"`
	Name           string      `json:"name"`
	AccountType    AccountType `json:"accountType"`
	CurrentBalance int         `json:"currentBalance"`
	IsDefault      bool        `json:"isDefault"`
	ReferenceID    *string     `json:"referenceId,omitempty"`
	ReferenceType  *string     `json:"referenceType,omitempty"`
	CreatedAt      time.Time   `json:"createdAt"`
}

type ActualDebtPayment struct {
	DebtID          string  `json:"debtId"`
	PersonName      string  `json:"personName"`
	Amount          float64 `json:"amount"`
	TransactionDate string  `json:"transactionDate"`
	Description     string  `json:"description"`
}

type ActualInstallmentPayment struct {
	InstallmentID   string  `json:"installmentId"`
	Name            string  `json:"name"`
	Amount          float64 `json:"amount"`
	TransactionDate string  `json:"transactionDate"`
	Description     string  `json:"description"`
}

type ActualPaymentsFilter struct {
	StartDate string `json:"startDate"`
	EndDate   string `json:"endDate"`
}

type ActualPaymentsReport struct {
	Installments     []*ActualInstallmentPayment `json:"installments"`
	Debts            []*ActualDebtPayment        `json:"debts"`
	TotalInstallment float64                     `json:"totalInstallment"`
	TotalDebt        float64                     `json:"totalDebt"`
	TotalPayments    float64                     `json:"totalPayments"`
}

type AddSavingsContributionInput struct {
	SavingsGoalID    uuid.UUID `json:"savingsGoalId"`
	Amount           int       `json:"amount"`
	ContributionDate time.Time `json:"contributionDate"`
	Notes            *string   `json:"notes,omitempty"`
}

type AuthPayload struct {
	Token        *string `json:"token,omitempty"`
	RefreshToken *string `json:"refreshToken,omitempty"`
	User         *User   `json:"user,omitempty"`
	Requires2fa  bool    `json:"requires2FA"`
	TempToken    *string `json:"tempToken,omitempty"`
}

type BalanceBreakdown struct {
	Total int `json:"total"`
	Count int `json:"count"`
}

type BalanceFilterInput struct {
	Period    BalancePeriod `json:"period"`
	StartDate *time.Time    `json:"startDate,omitempty"`
	EndDate   *time.Time    `json:"endDate,omitempty"`
}

type BalanceReport struct {
	PeriodLabel string            `json:"periodLabel"`
	StartDate   time.Time         `json:"startDate"`
	EndDate     time.Time         `json:"endDate"`
	Income      *IncomeBreakdown  `json:"income"`
	Expense     *ExpenseBreakdown `json:"expense"`
	Installment *BalanceBreakdown `json:"installment"`
	Debt        *BalanceBreakdown `json:"debt"`
	NetBalance  int               `json:"netBalance"`
	Status      BalanceStatus     `json:"status"`
}

type BalanceSummary struct {
	TotalIncome             int           `json:"totalIncome"`
	TotalExpense            int           `json:"totalExpense"`
	TotalInstallmentPayment int           `json:"totalInstallmentPayment"`
	TotalDebtPayment        int           `json:"totalDebtPayment"`
	NetBalance              int           `json:"netBalance"`
	Status                  BalanceStatus `json:"status"`
}

type Category struct {
	ID           uuid.UUID  `json:"id"`
	Name         string     `json:"name"`
	CreatedAt    time.Time  `json:"createdAt"`
	Expenses     []*Expense `json:"expenses"`
	ExpenseCount int        `json:"expenseCount"`
	TotalSpent   int        `json:"totalSpent"`
}

type CategorySummary struct {
	Category     *Category `json:"category"`
	TotalAmount  int       `json:"totalAmount"`
	ExpenseCount int       `json:"expenseCount"`
}

type CreateAccountInput struct {
	Name        string      `json:"name"`
	AccountType AccountType `json:"accountType"`
}

type CreateCategoryInput struct {
	Name string `json:"name"`
}

type CreateDebtInput struct {
	PersonName     string          `json:"personName"`
	ActualAmount   int             `json:"actualAmount"`
	LoanAmount     *int            `json:"loanAmount,omitempty"`
	PaymentType    DebtPaymentType `json:"paymentType"`
	MonthlyPayment *int            `json:"monthlyPayment,omitempty"`
	Tenor          *int            `json:"tenor,omitempty"`
	DueDate        *time.Time      `json:"dueDate,omitempty"`
	Notes          *string         `json:"notes,omitempty"`
}

type CreateExpenseInput struct {
	CategoryID  uuid.UUID  `json:"categoryId"`
	ItemName    string     `json:"itemName"`
	UnitPrice   int        `json:"unitPrice"`
	Quantity    int        `json:"quantity"`
	Notes       *string    `json:"notes,omitempty"`
	ExpenseDate *time.Time `json:"expenseDate,omitempty"`
}

type CreateExpenseTemplateGroupInput struct {
	Name         string                            `json:"name"`
	RecurringDay *int                              `json:"recurringDay,omitempty"`
	Notes        *string                           `json:"notes,omitempty"`
	Items        []*CreateExpenseTemplateItemInput `json:"items"`
}

type CreateExpenseTemplateItemInput struct {
	CategoryID uuid.UUID `json:"categoryId"`
	ItemName   string    `json:"itemName"`
	UnitPrice  int       `json:"unitPrice"`
	Quantity   int       `json:"quantity"`
}

type CreateIncomeCategoryInput struct {
	Name string `json:"name"`
}

type CreateIncomeInput struct {
	CategoryID  uuid.UUID  `json:"categoryId"`
	SourceName  string     `json:"sourceName"`
	Amount      int        `json:"amount"`
	IncomeType  IncomeType `json:"incomeType"`
	IncomeDate  *time.Time `json:"incomeDate,omitempty"`
	IsRecurring *bool      `json:"isRecurring,omitempty"`
	Notes       *string    `json:"notes,omitempty"`
}

type CreateInstallmentInput struct {
	Name           string    `json:"name"`
	ActualAmount   int       `json:"actualAmount"`
	LoanAmount     int       `json:"loanAmount"`
	MonthlyPayment int       `json:"monthlyPayment"`
	Tenor          int       `json:"tenor"`
	StartDate      time.Time `json:"startDate"`
	DueDay         int       `json:"dueDay"`
	Notes          *string   `json:"notes,omitempty"`
}

type CreateRecurringIncomeInput struct {
	CategoryID   uuid.UUID  `json:"categoryId"`
	SourceName   string     `json:"sourceName"`
	Amount       int        `json:"amount"`
	IncomeType   IncomeType `json:"incomeType"`
	RecurringDay int        `json:"recurringDay"`
	Notes        *string    `json:"notes,omitempty"`
}

type CreateSavingsGoalInput struct {
	Name         string    `json:"name"`
	TargetAmount int       `json:"targetAmount"`
	TargetDate   time.Time `json:"targetDate"`
	Icon         *string   `json:"icon,omitempty"`
	Notes        *string   `json:"notes,omitempty"`
}

type Dashboard struct {
	TotalActiveDebt                   int                `json:"totalActiveDebt"`
	TotalActiveInstallment            int                `json:"totalActiveInstallment"`
	TotalExpenseThisMonth             int                `json:"totalExpenseThisMonth"`
	TotalIncomeThisMonth              int                `json:"totalIncomeThisMonth"`
	TotalSavingsContributionThisMonth int                `json:"totalSavingsContributionThisMonth"`
	BalanceSummary                    *BalanceSummary    `json:"balanceSummary"`
	ActiveSavingsGoals                []*SavingsGoal     `json:"activeSavingsGoals"`
	ExpensesByCategory                []*CategorySummary `json:"expensesByCategory"`
	RecentExpenses                    []*Expense         `json:"recentExpenses"`
}

type Debt struct {
	ID                 uuid.UUID       `json:"id"`
	PersonName         string          `json:"personName"`
	ActualAmount       int             `json:"actualAmount"`
	LoanAmount         *int            `json:"loanAmount,omitempty"`
	PaymentType        DebtPaymentType `json:"paymentType"`
	MonthlyPayment     *int            `json:"monthlyPayment,omitempty"`
	Tenor              *int            `json:"tenor,omitempty"`
	DueDate            *time.Time      `json:"dueDate,omitempty"`
	Status             DebtStatus      `json:"status"`
	Notes              *string         `json:"notes,omitempty"`
	CreatedAt          time.Time       `json:"createdAt"`
	InterestAmount     *int            `json:"interestAmount,omitempty"`
	InterestPercentage *float64        `json:"interestPercentage,omitempty"`
	TotalToPay         int             `json:"totalToPay"`
	PaidAmount         int             `json:"paidAmount"`
	RemainingAmount    int             `json:"remainingAmount"`
	Payments           []*DebtPayment  `json:"payments"`
}

type DebtPayment struct {
	ID            uuid.UUID `json:"id"`
	PaymentNumber int       `json:"paymentNumber"`
	Amount        int       `json:"amount"`
	PaidAt        time.Time `json:"paidAt"`
	CreatedAt     time.Time `json:"createdAt"`
	Debt          *Debt     `json:"debt"`
}

type DeleteAccountInput struct {
	Password string `json:"password"`
}

type Expense struct {
	ID          uuid.UUID  `json:"id"`
	ItemName    string     `json:"itemName"`
	UnitPrice   int        `json:"unitPrice"`
	Quantity    int        `json:"quantity"`
	Total       int        `json:"total"`
	Notes       *string    `json:"notes,omitempty"`
	ExpenseDate *time.Time `json:"expenseDate,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
	Category    *Category  `json:"category"`
}

type ExpenseBreakdown struct {
	Total      int                `json:"total"`
	Count      int                `json:"count"`
	ByCategory []*CategorySummary `json:"byCategory"`
}

type ExpenseByCategoryGroup struct {
	Category    *Category `json:"category"`
	TotalAmount int       `json:"totalAmount"`
	Count       int       `json:"count"`
}

type ExpenseFilter struct {
	CategoryID *uuid.UUID `json:"categoryId,omitempty"`
	StartDate  *time.Time `json:"startDate,omitempty"`
	EndDate    *time.Time `json:"endDate,omitempty"`
}

type ExpenseSummary struct {
	Total      int                       `json:"total"`
	Count      int                       `json:"count"`
	ByCategory []*ExpenseByCategoryGroup `json:"byCategory"`
}

type ExpenseTemplateGroup struct {
	ID           uuid.UUID              `json:"id"`
	Name         string                 `json:"name"`
	RecurringDay *int                   `json:"recurringDay,omitempty"`
	Notes        *string                `json:"notes,omitempty"`
	Total        int                    `json:"total"`
	CreatedAt    time.Time              `json:"createdAt"`
	Items        []*ExpenseTemplateItem `json:"items"`
}

type ExpenseTemplateItem struct {
	ID        uuid.UUID `json:"id"`
	ItemName  string    `json:"itemName"`
	UnitPrice int       `json:"unitPrice"`
	Quantity  int       `json:"quantity"`
	Total     int       `json:"total"`
	CreatedAt time.Time `json:"createdAt"`
	Category  *Category `json:"category"`
}

type ExpensesWithSummary struct {
	Items   []*Expense      `json:"items"`
	Summary *ExpenseSummary `json:"summary"`
}

type ForecastSummary struct {
	AvailableMonths          []string                `json:"availableMonths"`
	SelectedMonth            string                  `json:"selectedMonth"`
	IncomeSummary            *IncomeSummary          `json:"incomeSummary"`
	ExpenseSummary           *ExpenseSummary         `json:"expenseSummary"`
	Payments                 *UpcomingPaymentsReport `json:"payments"`
	TotalSavingsContribution int                     `json:"totalSavingsContribution"`
}

type ForgotPasswordInput struct {
	Email string `json:"email"`
}

type HistorySummary struct {
	AvailableMonths          []string              `json:"availableMonths"`
	SelectedMonth            string                `json:"selectedMonth"`
	IncomeSummary            *IncomeSummary        `json:"incomeSummary"`
	ExpenseSummary           *ExpenseSummary       `json:"expenseSummary"`
	Payments                 *ActualPaymentsReport `json:"payments"`
	TotalSavingsContribution int                   `json:"totalSavingsContribution"`
}

type Income struct {
	ID          uuid.UUID       `json:"id"`
	SourceName  string          `json:"sourceName"`
	Amount      int             `json:"amount"`
	IncomeType  IncomeType      `json:"incomeType"`
	IncomeDate  time.Time       `json:"incomeDate"`
	IsRecurring bool            `json:"isRecurring"`
	Notes       *string         `json:"notes,omitempty"`
	CreatedAt   time.Time       `json:"createdAt"`
	Category    *IncomeCategory `json:"category"`
}

type IncomeBreakdown struct {
	Total      int                      `json:"total"`
	Count      int                      `json:"count"`
	ByCategory []*IncomeCategorySummary `json:"byCategory"`
	ByType     []*IncomeTypeSummary     `json:"byType"`
}

type IncomeByCategoryGroup struct {
	Category    *IncomeCategory `json:"category"`
	TotalAmount int             `json:"totalAmount"`
	Count       int             `json:"count"`
}

type IncomeByTypeGroup struct {
	IncomeType  IncomeType `json:"incomeType"`
	TotalAmount int        `json:"totalAmount"`
	Count       int        `json:"count"`
}

type IncomeCategory struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	CreatedAt   time.Time `json:"createdAt"`
	Incomes     []*Income `json:"incomes"`
	IncomeCount int       `json:"incomeCount"`
	TotalIncome int       `json:"totalIncome"`
}

type IncomeCategorySummary struct {
	Category    *IncomeCategory `json:"category"`
	TotalAmount int             `json:"totalAmount"`
	IncomeCount int             `json:"incomeCount"`
}

type IncomeFilter struct {
	CategoryID *uuid.UUID  `json:"categoryId,omitempty"`
	IncomeType *IncomeType `json:"incomeType,omitempty"`
	StartDate  *time.Time  `json:"startDate,omitempty"`
	EndDate    *time.Time  `json:"endDate,omitempty"`
}

type IncomeSummary struct {
	Total      int                      `json:"total"`
	Count      int                      `json:"count"`
	ByCategory []*IncomeByCategoryGroup `json:"byCategory"`
	ByType     []*IncomeByTypeGroup     `json:"byType"`
}

type IncomeTypeSummary struct {
	IncomeType  IncomeType `json:"incomeType"`
	TotalAmount int        `json:"totalAmount"`
	IncomeCount int        `json:"incomeCount"`
}

type IncomesWithSummary struct {
	Items   []*Income      `json:"items"`
	Summary *IncomeSummary `json:"summary"`
}

type Installment struct {
	ID                 uuid.UUID             `json:"id"`
	Name               string                `json:"name"`
	ActualAmount       int                   `json:"actualAmount"`
	LoanAmount         int                   `json:"loanAmount"`
	MonthlyPayment     int                   `json:"monthlyPayment"`
	Tenor              int                   `json:"tenor"`
	StartDate          time.Time             `json:"startDate"`
	DueDay             int                   `json:"dueDay"`
	Status             InstallmentStatus     `json:"status"`
	Notes              *string               `json:"notes,omitempty"`
	CreatedAt          time.Time             `json:"createdAt"`
	InterestAmount     int                   `json:"interestAmount"`
	InterestPercentage float64               `json:"interestPercentage"`
	PaidCount          int                   `json:"paidCount"`
	RemainingPayments  int                   `json:"remainingPayments"`
	RemainingAmount    int                   `json:"remainingAmount"`
	Payments           []*InstallmentPayment `json:"payments"`
}

type InstallmentPayment struct {
	ID            uuid.UUID    `json:"id"`
	PaymentNumber int          `json:"paymentNumber"`
	Amount        int          `json:"amount"`
	PaidAt        time.Time    `json:"paidAt"`
	CreatedAt     time.Time    `json:"createdAt"`
	Installment   *Installment `json:"installment"`
}

type LedgerSummary struct {
	TotalAssets      int `json:"totalAssets"`
	TotalLiabilities int `json:"totalLiabilities"`
	TotalIncome      int `json:"totalIncome"`
	TotalExpense     int `json:"totalExpense"`
	NetWorth         int `json:"netWorth"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type MonthYearInput struct {
	Month int `json:"month"`
	Year  int `json:"year"`
}

type Mutation struct {
}

type NotificationLog struct {
	ID           uuid.UUID `json:"id"`
	Type         string    `json:"type"`
	ReferenceID  uuid.UUID `json:"referenceId"`
	SentAt       time.Time `json:"sentAt"`
	EmailSubject *string   `json:"emailSubject,omitempty"`
	CreatedAt    time.Time `json:"createdAt"`
}

type Query struct {
}

type RecordDebtPaymentInput struct {
	DebtID uuid.UUID `json:"debtId"`
	Amount int       `json:"amount"`
	PaidAt time.Time `json:"paidAt"`
}

type RecordInstallmentPaymentInput struct {
	InstallmentID uuid.UUID `json:"installmentId"`
	Amount        int       `json:"amount"`
	PaidAt        time.Time `json:"paidAt"`
}

type RecurringIncome struct {
	ID           uuid.UUID       `json:"id"`
	SourceName   string          `json:"sourceName"`
	Amount       int             `json:"amount"`
	IncomeType   IncomeType      `json:"incomeType"`
	RecurringDay int             `json:"recurringDay"`
	IsActive     bool            `json:"isActive"`
	Notes        *string         `json:"notes,omitempty"`
	CreatedAt    time.Time       `json:"createdAt"`
	Category     *IncomeCategory `json:"category"`
}

type RegisterInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

type ResetPasswordInput struct {
	Token    string `json:"token"`
	Password string `json:"password"`
}

type SavingsContribution struct {
	ID               uuid.UUID    `json:"id"`
	Amount           int          `json:"amount"`
	ContributionDate time.Time    `json:"contributionDate"`
	Notes            *string      `json:"notes,omitempty"`
	CreatedAt        time.Time    `json:"createdAt"`
	SavingsGoal      *SavingsGoal `json:"savingsGoal"`
}

type SavingsGoal struct {
	ID              uuid.UUID              `json:"id"`
	Name            string                 `json:"name"`
	TargetAmount    int                    `json:"targetAmount"`
	CurrentAmount   int                    `json:"currentAmount"`
	TargetDate      time.Time              `json:"targetDate"`
	Icon            *string                `json:"icon,omitempty"`
	Status          SavingsGoalStatus      `json:"status"`
	Notes           *string                `json:"notes,omitempty"`
	Progress        float64                `json:"progress"`
	RemainingAmount int                    `json:"remainingAmount"`
	MonthlyTarget   int                    `json:"monthlyTarget"`
	CreatedAt       time.Time              `json:"createdAt"`
	Contributions   []*SavingsContribution `json:"contributions"`
}

type Transaction struct {
	ID              string              `json:"id"`
	TransactionDate time.Time           `json:"transactionDate"`
	Description     string              `json:"description"`
	Entries         []*TransactionEntry `json:"entries"`
	ReferenceID     *string             `json:"referenceId,omitempty"`
	ReferenceType   *string             `json:"referenceType,omitempty"`
	CreatedAt       time.Time           `json:"createdAt"`
}

type TransactionEntry struct {
	ID      string   `json:"id"`
	Account *Account `json:"account"`
	Debit   int      `json:"debit"`
	Credit  int      `json:"credit"`
}

type TransactionFilter struct {
	StartDate *time.Time `json:"startDate,omitempty"`
	EndDate   *time.Time `json:"endDate,omitempty"`
}

type TwoFAPayload struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	User         *User  `json:"user"`
}

type UpcomingDebtPayment struct {
	DebtID          string `json:"debtId"`
	PersonName      string `json:"personName"`
	MonthlyPayment  int    `json:"monthlyPayment"`
	DueDate         string `json:"dueDate"`
	RemainingAmount int    `json:"remainingAmount"`
	PaymentType     string `json:"paymentType"`
}

type UpcomingInstallmentPayment struct {
	InstallmentID     string `json:"installmentId"`
	Name              string `json:"name"`
	MonthlyPayment    int    `json:"monthlyPayment"`
	DueDay            int    `json:"dueDay"`
	DueDate           string `json:"dueDate"`
	RemainingAmount   int    `json:"remainingAmount"`
	RemainingPayments int    `json:"remainingPayments"`
}

type UpcomingPaymentsFilter struct {
	Month int `json:"month"`
	Year  int `json:"year"`
}

type UpcomingPaymentsReport struct {
	Installments     []*UpcomingInstallmentPayment `json:"installments"`
	Debts            []*UpcomingDebtPayment        `json:"debts"`
	TotalInstallment int                           `json:"totalInstallment"`
	TotalDebt        int                           `json:"totalDebt"`
	TotalPayments    int                           `json:"totalPayments"`
}

type UpdateAccountInput struct {
	Name string `json:"name"`
}

type UpdateCategoryInput struct {
	Name string `json:"name"`
}

type UpdateDebtInput struct {
	PersonName     *string          `json:"personName,omitempty"`
	ActualAmount   *int             `json:"actualAmount,omitempty"`
	LoanAmount     *int             `json:"loanAmount,omitempty"`
	PaymentType    *DebtPaymentType `json:"paymentType,omitempty"`
	MonthlyPayment *int             `json:"monthlyPayment,omitempty"`
	Tenor          *int             `json:"tenor,omitempty"`
	DueDate        *time.Time       `json:"dueDate,omitempty"`
	Status         *DebtStatus      `json:"status,omitempty"`
	Notes          *string          `json:"notes,omitempty"`
}

type UpdateExpenseInput struct {
	CategoryID  *uuid.UUID `json:"categoryId,omitempty"`
	ItemName    *string    `json:"itemName,omitempty"`
	UnitPrice   *int       `json:"unitPrice,omitempty"`
	Quantity    *int       `json:"quantity,omitempty"`
	Notes       *string    `json:"notes,omitempty"`
	ExpenseDate *time.Time `json:"expenseDate,omitempty"`
}

type UpdateExpenseTemplateGroupInput struct {
	Name         *string `json:"name,omitempty"`
	RecurringDay *int    `json:"recurringDay,omitempty"`
	Notes        *string `json:"notes,omitempty"`
}

type UpdateExpenseTemplateItemInput struct {
	CategoryID *uuid.UUID `json:"categoryId,omitempty"`
	ItemName   *string    `json:"itemName,omitempty"`
	UnitPrice  *int       `json:"unitPrice,omitempty"`
	Quantity   *int       `json:"quantity,omitempty"`
}

type UpdateIncomeCategoryInput struct {
	Name string `json:"name"`
}

type UpdateIncomeInput struct {
	CategoryID  *uuid.UUID  `json:"categoryId,omitempty"`
	SourceName  *string     `json:"sourceName,omitempty"`
	Amount      *int        `json:"amount,omitempty"`
	IncomeType  *IncomeType `json:"incomeType,omitempty"`
	IncomeDate  *time.Time  `json:"incomeDate,omitempty"`
	IsRecurring *bool       `json:"isRecurring,omitempty"`
	Notes       *string     `json:"notes,omitempty"`
}

type UpdateInstallmentInput struct {
	Name           *string            `json:"name,omitempty"`
	ActualAmount   *int               `json:"actualAmount,omitempty"`
	LoanAmount     *int               `json:"loanAmount,omitempty"`
	MonthlyPayment *int               `json:"monthlyPayment,omitempty"`
	Tenor          *int               `json:"tenor,omitempty"`
	StartDate      *time.Time         `json:"startDate,omitempty"`
	DueDay         *int               `json:"dueDay,omitempty"`
	Status         *InstallmentStatus `json:"status,omitempty"`
	Notes          *string            `json:"notes,omitempty"`
}

type UpdateNotificationSettingsInput struct {
	NotifyInstallment *bool `json:"notifyInstallment,omitempty"`
	NotifyDebt        *bool `json:"notifyDebt,omitempty"`
	NotifySavingsGoal *bool `json:"notifySavingsGoal,omitempty"`
	NotifyDaysBefore  *int  `json:"notifyDaysBefore,omitempty"`
}

type UpdateProfileInput struct {
	Name            *string `json:"name,omitempty"`
	Email           *string `json:"email,omitempty"`
	ProfileImage    *string `json:"profileImage,omitempty"`
	CurrentPassword *string `json:"currentPassword,omitempty"`
	Password        *string `json:"password,omitempty"`
}

type UpdateRecurringIncomeInput struct {
	CategoryID   *uuid.UUID  `json:"categoryId,omitempty"`
	SourceName   *string     `json:"sourceName,omitempty"`
	Amount       *int        `json:"amount,omitempty"`
	IncomeType   *IncomeType `json:"incomeType,omitempty"`
	RecurringDay *int        `json:"recurringDay,omitempty"`
	IsActive     *bool       `json:"isActive,omitempty"`
	Notes        *string     `json:"notes,omitempty"`
}

type UpdateSavingsGoalInput struct {
	Name         *string            `json:"name,omitempty"`
	TargetAmount *int               `json:"targetAmount,omitempty"`
	TargetDate   *time.Time         `json:"targetDate,omitempty"`
	Icon         *string            `json:"icon,omitempty"`
	Notes        *string            `json:"notes,omitempty"`
	Status       *SavingsGoalStatus `json:"status,omitempty"`
}

type User struct {
	ID                uuid.UUID  `json:"id"`
	Email             string     `json:"email"`
	Name              string     `json:"name"`
	ProfileImage      string     `json:"profileImage"`
	TwoFAEnabled      bool       `json:"twoFAEnabled"`
	NotifyInstallment bool       `json:"notifyInstallment"`
	NotifyDebt        bool       `json:"notifyDebt"`
	NotifySavingsGoal bool       `json:"notifySavingsGoal"`
	NotifyDaysBefore  int        `json:"notifyDaysBefore"`
	CreatedAt         time.Time  `json:"createdAt"`
	UpdatedAt         *time.Time `json:"updatedAt,omitempty"`
}

type Verify2FAInput struct {
	TempToken string `json:"tempToken"`
	Code      string `json:"code"`
}

type AccountType string

const (
	AccountTypeAsset     AccountType = "ASSET"
	AccountTypeLiability AccountType = "LIABILITY"
	AccountTypeIncome    AccountType = "INCOME"
	AccountTypeExpense   AccountType = "EXPENSE"
)

var AllAccountType = []AccountType{
	AccountTypeAsset,
	AccountTypeLiability,
	AccountTypeIncome,
	AccountTypeExpense,
}

func (e AccountType) IsValid() bool {
	switch e {
	case AccountTypeAsset, AccountTypeLiability, AccountTypeIncome, AccountTypeExpense:
		return true
	}
	return false
}

func (e AccountType) String() string {
	return string(e)
}

func (e *AccountType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AccountType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AccountType", str)
	}
	return nil
}

func (e AccountType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AccountType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AccountType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BalancePeriod string

const (
	BalancePeriodThisMonth BalancePeriod = "THIS_MONTH"
	BalancePeriodLastMonth BalancePeriod = "LAST_MONTH"
	BalancePeriodThisYear  BalancePeriod = "THIS_YEAR"
	BalancePeriodCustom    BalancePeriod = "CUSTOM"
)

var AllBalancePeriod = []BalancePeriod{
	BalancePeriodThisMonth,
	BalancePeriodLastMonth,
	BalancePeriodThisYear,
	BalancePeriodCustom,
}

func (e BalancePeriod) IsValid() bool {
	switch e {
	case BalancePeriodThisMonth, BalancePeriodLastMonth, BalancePeriodThisYear, BalancePeriodCustom:
		return true
	}
	return false
}

func (e BalancePeriod) String() string {
	return string(e)
}

func (e *BalancePeriod) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BalancePeriod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BalancePeriod", str)
	}
	return nil
}

func (e BalancePeriod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BalancePeriod) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BalancePeriod) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BalanceStatus string

const (
	BalanceStatusSurplus  BalanceStatus = "SURPLUS"
	BalanceStatusDeficit  BalanceStatus = "DEFICIT"
	BalanceStatusBalanced BalanceStatus = "BALANCED"
)

var AllBalanceStatus = []BalanceStatus{
	BalanceStatusSurplus,
	BalanceStatusDeficit,
	BalanceStatusBalanced,
}

func (e BalanceStatus) IsValid() bool {
	switch e {
	case BalanceStatusSurplus, BalanceStatusDeficit, BalanceStatusBalanced:
		return true
	}
	return false
}

func (e BalanceStatus) String() string {
	return string(e)
}

func (e *BalanceStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BalanceStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BalanceStatus", str)
	}
	return nil
}

func (e BalanceStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BalanceStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BalanceStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DebtPaymentType string

const (
	DebtPaymentTypeOneTime     DebtPaymentType = "ONE_TIME"
	DebtPaymentTypeInstallment DebtPaymentType = "INSTALLMENT"
)

var AllDebtPaymentType = []DebtPaymentType{
	DebtPaymentTypeOneTime,
	DebtPaymentTypeInstallment,
}

func (e DebtPaymentType) IsValid() bool {
	switch e {
	case DebtPaymentTypeOneTime, DebtPaymentTypeInstallment:
		return true
	}
	return false
}

func (e DebtPaymentType) String() string {
	return string(e)
}

func (e *DebtPaymentType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DebtPaymentType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DebtPaymentType", str)
	}
	return nil
}

func (e DebtPaymentType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DebtPaymentType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DebtPaymentType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DebtStatus string

const (
	DebtStatusActive    DebtStatus = "ACTIVE"
	DebtStatusCompleted DebtStatus = "COMPLETED"
)

var AllDebtStatus = []DebtStatus{
	DebtStatusActive,
	DebtStatusCompleted,
}

func (e DebtStatus) IsValid() bool {
	switch e {
	case DebtStatusActive, DebtStatusCompleted:
		return true
	}
	return false
}

func (e DebtStatus) String() string {
	return string(e)
}

func (e *DebtStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DebtStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DebtStatus", str)
	}
	return nil
}

func (e DebtStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DebtStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DebtStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type IncomeType string

const (
	IncomeTypeSalary     IncomeType = "SALARY"
	IncomeTypeFreelance  IncomeType = "FREELANCE"
	IncomeTypeInvestment IncomeType = "INVESTMENT"
	IncomeTypeGift       IncomeType = "GIFT"
	IncomeTypeBonus      IncomeType = "BONUS"
	IncomeTypeRefund     IncomeType = "REFUND"
	IncomeTypeBusiness   IncomeType = "BUSINESS"
	IncomeTypeOther      IncomeType = "OTHER"
)

var AllIncomeType = []IncomeType{
	IncomeTypeSalary,
	IncomeTypeFreelance,
	IncomeTypeInvestment,
	IncomeTypeGift,
	IncomeTypeBonus,
	IncomeTypeRefund,
	IncomeTypeBusiness,
	IncomeTypeOther,
}

func (e IncomeType) IsValid() bool {
	switch e {
	case IncomeTypeSalary, IncomeTypeFreelance, IncomeTypeInvestment, IncomeTypeGift, IncomeTypeBonus, IncomeTypeRefund, IncomeTypeBusiness, IncomeTypeOther:
		return true
	}
	return false
}

func (e IncomeType) String() string {
	return string(e)
}

func (e *IncomeType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = IncomeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid IncomeType", str)
	}
	return nil
}

func (e IncomeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *IncomeType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e IncomeType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InstallmentStatus string

const (
	InstallmentStatusActive    InstallmentStatus = "ACTIVE"
	InstallmentStatusCompleted InstallmentStatus = "COMPLETED"
)

var AllInstallmentStatus = []InstallmentStatus{
	InstallmentStatusActive,
	InstallmentStatusCompleted,
}

func (e InstallmentStatus) IsValid() bool {
	switch e {
	case InstallmentStatusActive, InstallmentStatusCompleted:
		return true
	}
	return false
}

func (e InstallmentStatus) String() string {
	return string(e)
}

func (e *InstallmentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InstallmentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InstallmentStatus", str)
	}
	return nil
}

func (e InstallmentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InstallmentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InstallmentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SavingsGoalStatus string

const (
	SavingsGoalStatusActive    SavingsGoalStatus = "ACTIVE"
	SavingsGoalStatusCompleted SavingsGoalStatus = "COMPLETED"
	SavingsGoalStatusCancelled SavingsGoalStatus = "CANCELLED"
)

var AllSavingsGoalStatus = []SavingsGoalStatus{
	SavingsGoalStatusActive,
	SavingsGoalStatusCompleted,
	SavingsGoalStatusCancelled,
}

func (e SavingsGoalStatus) IsValid() bool {
	switch e {
	case SavingsGoalStatusActive, SavingsGoalStatusCompleted, SavingsGoalStatusCancelled:
		return true
	}
	return false
}

func (e SavingsGoalStatus) String() string {
	return string(e)
}

func (e *SavingsGoalStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SavingsGoalStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SavingsGoalStatus", str)
	}
	return nil
}

func (e SavingsGoalStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SavingsGoalStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SavingsGoalStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
