// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Category struct {
	ID           uuid.UUID  `json:"id"`
	Name         string     `json:"name"`
	CreatedAt    time.Time  `json:"createdAt"`
	Expenses     []*Expense `json:"expenses"`
	ExpenseCount int        `json:"expenseCount"`
	TotalSpent   int        `json:"totalSpent"`
}

type CategorySummary struct {
	Category     *Category `json:"category"`
	TotalAmount  int       `json:"totalAmount"`
	ExpenseCount int       `json:"expenseCount"`
}

type CreateCategoryInput struct {
	Name string `json:"name"`
}

type CreateDebtInput struct {
	PersonName     string          `json:"personName"`
	ActualAmount   int             `json:"actualAmount"`
	LoanAmount     *int            `json:"loanAmount,omitempty"`
	PaymentType    DebtPaymentType `json:"paymentType"`
	MonthlyPayment *int            `json:"monthlyPayment,omitempty"`
	Tenor          *int            `json:"tenor,omitempty"`
	DueDate        *time.Time      `json:"dueDate,omitempty"`
	Notes          *string         `json:"notes,omitempty"`
}

type CreateExpenseInput struct {
	CategoryID  uuid.UUID  `json:"categoryId"`
	ItemName    string     `json:"itemName"`
	UnitPrice   int        `json:"unitPrice"`
	Quantity    int        `json:"quantity"`
	Notes       *string    `json:"notes,omitempty"`
	ExpenseDate *time.Time `json:"expenseDate,omitempty"`
}

type CreateExpenseTemplateInput struct {
	CategoryID   uuid.UUID `json:"categoryId"`
	ItemName     string    `json:"itemName"`
	UnitPrice    int       `json:"unitPrice"`
	Quantity     int       `json:"quantity"`
	RecurringDay *int      `json:"recurringDay,omitempty"`
	Notes        *string   `json:"notes,omitempty"`
}

type CreateInstallmentInput struct {
	Name           string    `json:"name"`
	ActualAmount   int       `json:"actualAmount"`
	LoanAmount     int       `json:"loanAmount"`
	MonthlyPayment int       `json:"monthlyPayment"`
	Tenor          int       `json:"tenor"`
	StartDate      time.Time `json:"startDate"`
	DueDay         int       `json:"dueDay"`
	Notes          *string   `json:"notes,omitempty"`
}

type Dashboard struct {
	TotalActiveDebt        int                `json:"totalActiveDebt"`
	TotalActiveInstallment int                `json:"totalActiveInstallment"`
	TotalExpenseThisMonth  int                `json:"totalExpenseThisMonth"`
	UpcomingInstallments   []*Installment     `json:"upcomingInstallments"`
	UpcomingDebts          []*Debt            `json:"upcomingDebts"`
	ExpensesByCategory     []*CategorySummary `json:"expensesByCategory"`
	RecentExpenses         []*Expense         `json:"recentExpenses"`
}

type Debt struct {
	ID                 uuid.UUID       `json:"id"`
	PersonName         string          `json:"personName"`
	ActualAmount       int             `json:"actualAmount"`
	LoanAmount         *int            `json:"loanAmount,omitempty"`
	PaymentType        DebtPaymentType `json:"paymentType"`
	MonthlyPayment     *int            `json:"monthlyPayment,omitempty"`
	Tenor              *int            `json:"tenor,omitempty"`
	DueDate            *time.Time      `json:"dueDate,omitempty"`
	Status             DebtStatus      `json:"status"`
	Notes              *string         `json:"notes,omitempty"`
	CreatedAt          time.Time       `json:"createdAt"`
	InterestAmount     *int            `json:"interestAmount,omitempty"`
	InterestPercentage *float64        `json:"interestPercentage,omitempty"`
	TotalToPay         int             `json:"totalToPay"`
	PaidAmount         int             `json:"paidAmount"`
	RemainingAmount    int             `json:"remainingAmount"`
	Payments           []*DebtPayment  `json:"payments"`
}

type DebtPayment struct {
	ID            uuid.UUID `json:"id"`
	PaymentNumber int       `json:"paymentNumber"`
	Amount        int       `json:"amount"`
	PaidAt        time.Time `json:"paidAt"`
	CreatedAt     time.Time `json:"createdAt"`
	Debt          *Debt     `json:"debt"`
}

type Expense struct {
	ID          uuid.UUID  `json:"id"`
	ItemName    string     `json:"itemName"`
	UnitPrice   int        `json:"unitPrice"`
	Quantity    int        `json:"quantity"`
	Total       int        `json:"total"`
	Notes       *string    `json:"notes,omitempty"`
	ExpenseDate *time.Time `json:"expenseDate,omitempty"`
	CreatedAt   time.Time  `json:"createdAt"`
	Category    *Category  `json:"category"`
}

type ExpenseFilter struct {
	CategoryID *uuid.UUID `json:"categoryId,omitempty"`
	StartDate  *time.Time `json:"startDate,omitempty"`
	EndDate    *time.Time `json:"endDate,omitempty"`
}

type ExpenseTemplate struct {
	ID           uuid.UUID `json:"id"`
	ItemName     string    `json:"itemName"`
	UnitPrice    int       `json:"unitPrice"`
	Quantity     int       `json:"quantity"`
	Total        int       `json:"total"`
	RecurringDay *int      `json:"recurringDay,omitempty"`
	Notes        *string   `json:"notes,omitempty"`
	CreatedAt    time.Time `json:"createdAt"`
	Category     *Category `json:"category"`
}

type Installment struct {
	ID                 uuid.UUID             `json:"id"`
	Name               string                `json:"name"`
	ActualAmount       int                   `json:"actualAmount"`
	LoanAmount         int                   `json:"loanAmount"`
	MonthlyPayment     int                   `json:"monthlyPayment"`
	Tenor              int                   `json:"tenor"`
	StartDate          time.Time             `json:"startDate"`
	DueDay             int                   `json:"dueDay"`
	Status             InstallmentStatus     `json:"status"`
	Notes              *string               `json:"notes,omitempty"`
	CreatedAt          time.Time             `json:"createdAt"`
	InterestAmount     int                   `json:"interestAmount"`
	InterestPercentage float64               `json:"interestPercentage"`
	PaidCount          int                   `json:"paidCount"`
	RemainingPayments  int                   `json:"remainingPayments"`
	RemainingAmount    int                   `json:"remainingAmount"`
	Payments           []*InstallmentPayment `json:"payments"`
}

type InstallmentPayment struct {
	ID            uuid.UUID    `json:"id"`
	PaymentNumber int          `json:"paymentNumber"`
	Amount        int          `json:"amount"`
	PaidAt        time.Time    `json:"paidAt"`
	CreatedAt     time.Time    `json:"createdAt"`
	Installment   *Installment `json:"installment"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RecordDebtPaymentInput struct {
	DebtID uuid.UUID `json:"debtId"`
	Amount int       `json:"amount"`
	PaidAt time.Time `json:"paidAt"`
}

type RecordInstallmentPaymentInput struct {
	InstallmentID uuid.UUID `json:"installmentId"`
	Amount        int       `json:"amount"`
	PaidAt        time.Time `json:"paidAt"`
}

type RegisterInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

type UpdateCategoryInput struct {
	Name string `json:"name"`
}

type UpdateDebtInput struct {
	PersonName     *string          `json:"personName,omitempty"`
	ActualAmount   *int             `json:"actualAmount,omitempty"`
	LoanAmount     *int             `json:"loanAmount,omitempty"`
	PaymentType    *DebtPaymentType `json:"paymentType,omitempty"`
	MonthlyPayment *int             `json:"monthlyPayment,omitempty"`
	Tenor          *int             `json:"tenor,omitempty"`
	DueDate        *time.Time       `json:"dueDate,omitempty"`
	Status         *DebtStatus      `json:"status,omitempty"`
	Notes          *string          `json:"notes,omitempty"`
}

type UpdateExpenseInput struct {
	CategoryID  *uuid.UUID `json:"categoryId,omitempty"`
	ItemName    *string    `json:"itemName,omitempty"`
	UnitPrice   *int       `json:"unitPrice,omitempty"`
	Quantity    *int       `json:"quantity,omitempty"`
	Notes       *string    `json:"notes,omitempty"`
	ExpenseDate *time.Time `json:"expenseDate,omitempty"`
}

type UpdateExpenseTemplateInput struct {
	CategoryID   *uuid.UUID `json:"categoryId,omitempty"`
	ItemName     *string    `json:"itemName,omitempty"`
	UnitPrice    *int       `json:"unitPrice,omitempty"`
	Quantity     *int       `json:"quantity,omitempty"`
	RecurringDay *int       `json:"recurringDay,omitempty"`
	Notes        *string    `json:"notes,omitempty"`
}

type UpdateInstallmentInput struct {
	Name           *string            `json:"name,omitempty"`
	ActualAmount   *int               `json:"actualAmount,omitempty"`
	LoanAmount     *int               `json:"loanAmount,omitempty"`
	MonthlyPayment *int               `json:"monthlyPayment,omitempty"`
	Tenor          *int               `json:"tenor,omitempty"`
	StartDate      *time.Time         `json:"startDate,omitempty"`
	DueDay         *int               `json:"dueDay,omitempty"`
	Status         *InstallmentStatus `json:"status,omitempty"`
	Notes          *string            `json:"notes,omitempty"`
}

type UpdateProfileInput struct {
	Name     *string `json:"name,omitempty"`
	Password *string `json:"password,omitempty"`
}

type User struct {
	ID        uuid.UUID  `json:"id"`
	Email     string     `json:"email"`
	Name      string     `json:"name"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

type DebtPaymentType string

const (
	DebtPaymentTypeOneTime     DebtPaymentType = "ONE_TIME"
	DebtPaymentTypeInstallment DebtPaymentType = "INSTALLMENT"
)

var AllDebtPaymentType = []DebtPaymentType{
	DebtPaymentTypeOneTime,
	DebtPaymentTypeInstallment,
}

func (e DebtPaymentType) IsValid() bool {
	switch e {
	case DebtPaymentTypeOneTime, DebtPaymentTypeInstallment:
		return true
	}
	return false
}

func (e DebtPaymentType) String() string {
	return string(e)
}

func (e *DebtPaymentType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DebtPaymentType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DebtPaymentType", str)
	}
	return nil
}

func (e DebtPaymentType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type DebtStatus string

const (
	DebtStatusActive    DebtStatus = "ACTIVE"
	DebtStatusCompleted DebtStatus = "COMPLETED"
)

var AllDebtStatus = []DebtStatus{
	DebtStatusActive,
	DebtStatusCompleted,
}

func (e DebtStatus) IsValid() bool {
	switch e {
	case DebtStatusActive, DebtStatusCompleted:
		return true
	}
	return false
}

func (e DebtStatus) String() string {
	return string(e)
}

func (e *DebtStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DebtStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DebtStatus", str)
	}
	return nil
}

func (e DebtStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type InstallmentStatus string

const (
	InstallmentStatusActive    InstallmentStatus = "ACTIVE"
	InstallmentStatusCompleted InstallmentStatus = "COMPLETED"
)

var AllInstallmentStatus = []InstallmentStatus{
	InstallmentStatusActive,
	InstallmentStatusCompleted,
}

func (e InstallmentStatus) IsValid() bool {
	switch e {
	case InstallmentStatusActive, InstallmentStatusCompleted:
		return true
	}
	return false
}

func (e InstallmentStatus) String() string {
	return string(e)
}

func (e *InstallmentStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InstallmentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InstallmentStatus", str)
	}
	return nil
}

func (e InstallmentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
