package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/azzamdhx/moneybro/backend/internal/graph/model"
	"github.com/azzamdhx/moneybro/backend/internal/middleware"
	"github.com/azzamdhx/moneybro/backend/internal/utils"
)

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context) ([]*model.NotificationLog, error) {
	userID, ok := middleware.GetUserID(ctx)
	if !ok {
		return nil, utils.ErrUnauthorized
	}

	logs, err := r.Services.Notification.GetByUserID(userID)
	if err != nil {
		return nil, err
	}

	result := make([]*model.NotificationLog, len(logs))
	for i, log := range logs {
		result[i] = &model.NotificationLog{
			ID:           log.ID,
			Type:         string(log.Type),
			ReferenceID:  log.ReferenceID,
			SentAt:       log.SentAt,
			EmailSubject: log.EmailSubject,
			CreatedAt:    log.CreatedAt,
		}
	}

	return result, nil
}
